const baseDevice = {
  id: "fr970",
  name: "Forerunner 970",
  width: 454,
  height: 454,
  capabilities: {
    apiLevel: "6.0.0",
    chartSources: [
      "heartRate",
      "bodyBattery",
      "stress",
      "oxygen",
      "elevation",
      "pressure",
      "temperature",
    ],
    onWatchSettings: true,
    verification: "sdk-compiled",
    complications: [
      "battery",
      "altitude",
      "pressure",
      "race5k",
      "race10k",
      "raceHalf",
      "raceMarathon",
      "heartRate",
      "bodyBattery",
      "stress",
      "recovery",
      "steps",
      "floors",
      "calories",
      "intensityMinutes",
      "runDistance",
      "bikeDistance",
      "vo2Run",
      "vo2Bike",
      "pulseOx",
      "respiration",
      "notifications",
    ],
    complicationHold: true,
    alwaysOn: true,
    lowBattery: true,
    nightLayout: true,
    doNotDisturb: true,
    layers: [
      "time",
      "date",
      "steps",
      "battery",
      "text",
      "heartRate",
      "calories",
      "distance",
      "floors",
      "activeMinutes",
      "bodyBattery",
      "stress",
      "recovery",
      "weather",
      "progress",
      "chart",
      "complication",
      "status",
      "shape",
      "icon",
      "image",
    ],
  },
  power: {
    defaultLowBatteryThreshold: 10,
    minLowBatteryThreshold: 1,
    maxLowBatteryThreshold: 30,
    alwaysOn: {
      fontSize: 48,
      color: "#777777",
      maxLuminance: 0.1,
      clipWidth: 454,
      clipHeight: 454,
      centerX: 227,
      centerY: 227,
      shiftY: 0,
    },
  },
  family: "Forerunner",
  display: "AMOLED",
  shape: "Round",
  category: "Running",
  supported: true,
  slug: "forerunner-970",
  preview: "/images/devices/forerunner-970-preview.png",
  frame: {
    image: "/images/devices/forerunner-970-frame.png",
    width: 755,
    height: 840,
    screenX: 154,
    screenY: 190,
    presentationWidth: 494,
    bezelRadius: 267,
  },
} as const;

export const devices = [
  baseDevice,
  {
    ...baseDevice,
    id: "fenix847mm",
    name: "Fēnix 8 AMOLED",
    slug: "fenix-8-amoled",
    family: "Fēnix",
    category: "Outdoor",
    capabilities: {
      ...baseDevice.capabilities,
      apiLevel: "6.0.0",
      onWatchSettings: true,
      complicationHold: true,
    },
    preview: "/images/devices/fenix-8-amoled-preview.png",
    frame: {
      image: "/images/devices/fenix-8-amoled-frame.png",
      width: 713,
      height: 921,
      screenX: 134,
      screenY: 221,
      presentationWidth: 494,
      bezelRadius: 252,
    },
  },
  {
    ...baseDevice,
    id: "fenix8pro47mm",
    name: "Fēnix 8 Pro AMOLED",
    slug: "fenix-8-pro-amoled",
    family: "Fēnix",
    category: "Outdoor",
    capabilities: {
      ...baseDevice.capabilities,
      apiLevel: "6.0.0",
      onWatchSettings: true,
      complicationHold: true,
    },
    preview: "/images/devices/fenix-8-pro-amoled-preview.png",
    frame: {
      image: "/images/devices/fenix-8-pro-amoled-frame.png",
      width: 675,
      height: 887,
      screenX: 116,
      screenY: 209,
      presentationWidth: 494,
      bezelRadius: 252,
    },
  },
  {
    ...baseDevice,
    id: "fr965",
    name: "Forerunner 965",
    slug: "forerunner-965",
    family: "Forerunner",
    category: "Running",
    capabilities: {
      ...baseDevice.capabilities,
      apiLevel: "5.2.0",
      onWatchSettings: false,
      complicationHold: false,
    },
    preview: "/images/devices/forerunner-965-preview.png",
    frame: {
      image: "/images/devices/forerunner-965-frame.png",
      width: 682,
      height: 913,
      screenX: 113,
      screenY: 233,
      presentationWidth: 494,
      bezelRadius: 252,
    },
  },
  {
    ...baseDevice,
    id: "fr57047mm",
    name: "Forerunner 570 47 mm",
    slug: "forerunner-570-47mm",
    family: "Forerunner",
    category: "Running",
    capabilities: {
      ...baseDevice.capabilities,
      apiLevel: "6.0.0",
    },
    preview: "/images/devices/forerunner-570-47mm-preview.png",
    frame: {
      image: "/images/devices/forerunner-570-47mm-frame.png",
      width: 755,
      height: 840,
      screenX: 154,
      screenY: 190,
      presentationWidth: 494,
      bezelRadius: 267,
    },
  },
  {
    ...baseDevice,
    id: "venu3",
    name: "Venu 3",
    slug: "venu-3",
    family: "Venu",
    category: "Lifestyle",
    capabilities: {
      ...baseDevice.capabilities,
      apiLevel: "5.2.0",
      onWatchSettings: false,
      complicationHold: false,
    },
    preview: "/images/devices/venu-3-preview.png",
    frame: {
      image: "/images/devices/venu-3-frame.png",
      width: 636,
      height: 882,
      screenX: 91,
      screenY: 206,
      presentationWidth: 494,
      bezelRadius: 252,
    },
  },
  {
    ...baseDevice,
    id: "venu445mm",
    name: "Venu 4 45 mm",
    slug: "venu-4-45mm",
    family: "Venu",
    category: "Lifestyle",
    capabilities: {
      ...baseDevice.capabilities,
      apiLevel: "6.0.0",
    },
    preview: "/images/devices/venu-4-45mm-preview.png",
    frame: {
      image: "/images/devices/venu-4-45mm-frame.png",
      width: 650,
      height: 902,
      screenX: 98,
      screenY: 223,
      presentationWidth: 494,
      bezelRadius: 252,
    },
  },
  {
    ...baseDevice,
    id: "fenix947mm",
    name: "Fēnix 9 AMOLED",
    slug: "fenix-9-amoled",
    family: "Fēnix",
    category: "Outdoor",
    capabilities: {
      ...baseDevice.capabilities,
      apiLevel: "6.0.0",
    },
    preview: "/images/devices/fenix-9-amoled-preview.png",
    frame: {
      image: "/images/devices/fenix-9-amoled-frame.png",
      width: 680,
      height: 937,
      screenX: 106,
      screenY: 233,
      presentationWidth: 494,
      bezelRadius: 267,
    },
  },
] as const;

export type Device = (typeof devices)[number];

export const getDeviceBySlug = (slug: string) =>
  devices.find((device) => device.slug === slug);

export const getDeviceById = (id: string) =>
  devices.find((device) => device.id === id);
